name: Build and Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-deploy-storybook:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Run build script
        run: yarn build-storybook
      - name: Deploy to `storybook-static` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
        with:
          # This `PUBLISH_DOCS_TOKEN` needs to be manually set per-repository.
          # Look in the repository settings under "Environments", and set this token in the `github-pages` environment.
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: storybook-static
